# -*- coding: utf-8 -*-
"""Datetime

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEhruWf43OeQkiV2jZSv7w_b98CMXx5l
"""

import datetime
time_now = datetime.datetime.now()
print(time_now)